### ISSUE TITLE
Error response from daemon: Unable to remove filesystem for ab68b000adfca007 ...

### ISSUE THREAD

**Issue by ksprider** [monitoringartist/zabbix-agent-xxl#11]
Hello. 

docker-compose.yml

```
zabbix-agent-xxl:
    image: monitoringartist/zabbix-agent-xxl-limited:latest
    hostname: agent1
    ports:
        - "10050:10050"
    volumes:
        - /:/rootfs
        - /var/run:/var/run
    environment:
        - ZA_Server=192.168.2.176
        - ZA_ServerActive=192.168.2.176
```

```
docker-compose up -d
```

output:

```
[root@localhost zabbix-agent]# docker-compose up -d
Creating zabbixagent_zabbix-agent-xxl_1
Error response from daemon: Unable to remove filesystem for ab68b000adfca007cfa18d2f4c12c31c60818ace86c27c3a61afd53d6d05e073: remove /var/lib/docker/containers/ab68b000adfca007cfa18d2f4c12c31c60818ace86c27c3a61afd53d6d05e073/shm: device or resource busy
[root@localhost zabbix-agent]# 
```

OS:

```
LSB Version:    :core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.2.1511 (Core) 
Release:        7.2.1511
Codename:       Core
```

```
[root@localhost zabbix-agent]# docker logs b5792366ef21
Zocker XXL v0.9.3b public limited version
Copyright (C) 2014-2016 Jan Garaj - www.monitoringartist.com 
Freeware licence - Usage of this binary is restricted to oficial monitoringartist Docker images only.
Starting Zabbix Agent [agent1]. Zabbix 3.0.3 XXL (2016-06-16) (revision {ZABBIX_REVISION}).
Press Ctrl+C to exit.

     8:20160619:181500.031 Starting Zabbix Agent [agent1]. Zabbix 3.0.3 XXL (2016-06-16) (revision {ZABBIX_REVISION}).
     8:20160619:181500.032 **** Enabled features ****
     8:20160619:181500.032 IPv6 support:          YES
     8:20160619:181500.032 TLS support:           YES
     8:20160619:181500.032 **************************
     8:20160619:181500.032 using configuration file: /etc/zabbix/zabbix_agentd.conf
     8:20160619:181500.040 loaded modules: zabbix_module_docker.so, zabbix_module_stress.so
     8:20160619:181500.041 agent #0 started [main process]
    10:20160619:181500.042 agent #1 started [collector]
    11:20160619:181500.043 agent #2 started [listener #1]
    12:20160619:181500.043 agent #3 started [listener #2]
    13:20160619:181500.044 agent #4 started [listener #3]
    14:20160619:181500.044 agent #5 started [active checks #1]
    14:20160619:181503.058 active check configuration update from [192.168.2.176:10051] started to fail (ZBX_TCP_READ() timed out)
```

```
[root@localhost zabbix-agent]# docker -v
Docker version 1.11.2, build b9f10c9
```

```
[root@localhost zabbix-agent]# telnet 192.168.2.176 10051
Trying 192.168.2.176...
Connected to 192.168.2.176.
Escape character is '^]'.
Connection closed by foreign host.
```
