### ISSUE TITLE
Error #3 on host with userns enabled

### ISSUE THREAD

**Issue by sergsadovyi** [monitoringartist/zabbix-agent-xxl#12]
Hello. I'm trying to launch zabbix agent on CentOS 7.2 host with enabled user namespaces for docker. And agent container falls with Error #3 message.

**docker -v**

```
Docker version 1.11.2, build b9f10c9
```

**docker daemon flags**

```
docker daemon -H tcp://0.0.0.0:2376 -H unix:///var/run/docker.sock --userns-remap=dcu --storage-driver devicemapper --storage-opt=dm.thinpooldev=/dev/mapper/docker-thinpool --storage-opt dm.use_deferred_removal=true --tlsverify --tlscacert /etc/docker/ca.pem --tlscert /etc/docker/server.pem --tlskey /etc/docker/server-key.pem --label provider=generic
```

**docker-compose.yml**

```
version: "2"

services:
  agent:
    image: monitoringartist/zabbix-agent-xxl-limited
    container_name: monitoring_agent
    hostname: hope.ua
    ports:
      - "10050:10050"
    volumes:
      - /:/rootfs
      - /var/run:/var/run
    environment:
      ZA_Server: <zabbix.server>
    restart: always
```

**Logs** of docker container:

```
Zocker XXL v0.9.4b public limited version
Copyright (C) 2014-2016 Jan Garaj - www.monitoringartist.com
Freeware licence - Usage of this binary is restricted to official monitoringartist Docker images only.
Error #3
```
