### ISSUE TITLE
Cannot open metric file: '/sys/fs/cgroup/memory/.../memory.stat'

### ISSUE THREAD

**Issue by sizerus** [monitoringartist/zabbix-agent-xxl#22]
My system is RHEL 7.3, docker version 1.12.5, build 047e51b/1.12.5, docker-compose version 1.10.0, build 4bd6f1a.
Selinux & user namespace's are enabled.

```
docker-compose.yml:
version: '2.1'
services:
    zocker:
        container_name: zocker
        image: monitoringartist/zabbix-agent-xxl-limited
        ports:
            - "10060:10050"
        hostname: $HOSTNAME 
        volumes: 
            - /:/rootfs:ro,z
            - /var/run:/var/run:ro,z
        environment:
            - ZA_Server=10.0.0.1
        userns_mode: host
        privileged: true
```

In logs:

```
13:20170220:133750.978 Cannot open metric file: '/sys/fs/cgroup/memory/d85758f142afcc4887f3bc2dcbae682e9b60cc63e487d530e225835e953d5747/memory.stat'
11:20170220:133751.981 Cannot open metric file: '/sys/fs/cgroup/memory/174aaa981703620fec6c8695289b6623390d1c04cd28a369bc1f1479106f2131/memory.stat'
```

Actually this 2 files are here:

```
/sys/fs/cgroup/memory/system.slice/docker-d85758f142afcc4887f3bc2dcbae682e9b60cc63e487d530e225835e953d5747.scope/memory.stat
/sys/fs/cgroup/memory/system.slice/docker-174aaa981703620fec6c8695289b6623390d1c04cd28a369bc1f1479106f2131.scope/memory.stat
```

Can you suggest some solutions?
